version: 0.1.2.2
description: Please see the readme on Github at <https://github.com/tek/polysemy-time>
license: BSD-2-Clause-Patent
author: Torsten Schmits
maintainer: tek@tryp.io
copyright: 2021 Torsten Schmits
category: Time
build-type: Simple
extra-source-files:
  - readme.md
  - changelog.md
